modLoader = "javafml"
loaderVersion = "[39,)"
license = "MIT"

[[mods]]
modId = "i18nupdatemod"
version = "${version}"
displayName = "I18nUpdateMod Non-LTS Architectury"
credits= "TartaricAcid, baka-gourd, exzhawk"
authors = "TexTrue, TexTrueStudio"
description = '''
自动汉化更新
'''
logoFile = "icon.png"

[[dependencies.i18nupdatemod]]
modId = "forge"
mandatory = true
versionRange = "[39,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.i18nupdatemod]]
modId = "minecraft"
mandatory = true
versionRange = "[1.18,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.i18nupdatemod]]
modId = "architectury"
mandatory = true
versionRange = "[4.9.83,)"
ordering = "AFTER"
side = "BOTH"