modLoader = "javafml"
loaderVersion = "[35,)"
license = "GPLv3"

[[mods]]
modId = "i18nupdatemod"
version = "${version}"
displayName = "I18nUpdateMod Non-LTS Architectury"
credits= "TartaricAcid, baka-gourd, exzhawk"
authors = "TexTrue, TexTrueStudio"
description = '''
自动汉化更新
'''
logoFile = "icon.png"

[[dependencies.i18nupdatemod]]
modId = "forge"
mandatory = true
versionRange = "[35,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.i18nupdatemod]]
modId = "minecraft"
mandatory = true
versionRange = "[1.16.4,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.i18nupdatemod]]
modId = "architectury"
mandatory = true
versionRange = "[1.32.66,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.i18nupdatemod]]
modId = "cloth-config"
mandatory = true
versionRange = "[4,)"
ordering = "NONE"
side = "BOTH"