modLoader="javafml"
loaderVersion="[39,)"
license="MIT"

[[mods]]
    modId="i18nupdatemod"
    version="${file.jarVersion}"
    displayName="i18nUpdateMod-NLTS"
    authors="TartaricAcid, baka-gourd, exzhawk"
    description="自动汉化更新模组"