modLoader="javafml"
loaderVersion="[40,)"
license="MIT"

[[mods]]
modId="i18nupdatemod"
version="${version}"
displayName="I18nUpdateMod Non-LTS"
logoFile="assets/i18n/icon.png"
credits="TartaricAcid, baka-gourd, exzhawk"
authors="TexTrue"
description='''
自动汉化更新模组
'''