modLoader="javafml"
loaderVersion="[40,)"
license="MIT"

[[mods]]
    modId="i18nupdatemod"
    version="${file.jarVersion}"
    displayName="I18nUpdateMod2 Non-LTS"
    authors="TartaricAcid, baka-gourd, exzhawk"
    description="自动汉化更新模组（非长期支持版）"